baseURL = 'https://mirmeep.github.io/prints-shop/'
languageCode = 'en-us'
title = 'DEV Art Hub Studio LLC'

[params]
  description = "WARNING: This site is used for DEVELOPMENT purposes only. ANY PRODUCT LISTED ON THIS SITE IS A TEST DUMMY."

[caches]
  [caches.images]
    dir = ':cacheDir/images'