baseURL = 'https://mnpprints.store/'
languageCode = 'en-us'
title = "Miranda Peak's Prints"

[params]
  description = "Hi! Welcome to my store 🙂. Please note I do US SHIPPING ONLY. Sorry for my global friends 😞. Thank you."

  [params.footer]
    [params.footer.info]
      title = "Information"
      [[params.footer.info.link]]
        name = "Terms and Conditions"
        url  = "policies/terms"
      [[params.footer.info.link]]
        name = "Privacy Policy"
        url  = "policies/privacy"
      [[params.footer.info.link]]
        name = "Shipping Policy"
        url  = "policies/shipping"
      [[params.footer.info.link]]
        name = "Return Policy"
        url  = "policies/returns"
[markup.goldmark.renderHooks.image]
  enableDefault = true

[markup.goldmark.renderHooks.link]
  enableDefault = true

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'

[caches]
  [caches.images]
    dir = ':cacheDir/images'