baseURL = 'https://mnpprints.store/'
languageCode = 'en-us'
title = "Miranda's Prints Shop"

[params]
  description = "Hi! Welcome to my store 🙂. This website is currently under development so orders won't go through, but feel free to take a look."

[markup.goldmark.renderHooks.image]
  enableDefault = true

[markup.goldmark.renderHooks.link]
  enableDefault = true

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'

[caches]
  [caches.images]
    dir = ':cacheDir/images'